let shopItemsData = [
    {
      id: "ckr1",
      name: "Jollof Rice",
      price: 500,
      img: "./assets/images/jollof-rice.jpg",
    },
    {
      id: "ckr2",
      name: "Fried Rice",
      price: 700,
      img: "assets/images/fried_rice.jpg",
    },
    {
      id: "ckr3",
      name: "Efo Egusi With Goat Meat",
      price: 900,
      img: "./assets/images/Efo-Egusi.jpg",
    },
    {
      id: "ckr4",
      name: "Shredded Chicken Sauce",
      price: 700,
      img: "./assets/images/scs.jpg",
    },
    {
      id: "ckr5",
      name: "Stew with Turkey",
      price: 1000,
      img: "./assets/images/stew-with-turkey.jpg",
    },
    {
      id: "ckr6",
      name: "Stew with Soft Chicken",
      price: 1000,
      img: "./assets/images/stew_with_soft_chicken.png",
    },
    {
      id: "ckr7",
      name: "Stew with Goat Meat",
      price: 1000,
      img: "./assets/images/stew_with_goat_meat.png",
    },
    {
      id: "ckr8",
      name: "SeaFood Okra Soup",
      price: 900,
      img: "./assets/images/seafood_okra_soup.png",
    },
    {
      id: "ckr9",
      name: "Ogbono with Goat Meat",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr10",
      name: "Efo Riro with Beef",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr11",
      name: "Efo Riro with Assorted",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr12",
      name: "Stew with Hard Chicken",
      price: 1000,
      img: "./assets/images/stew-with-hard-chicken.png",
    },
    {
      id: "ckr13",
      name: "Stew with Beef",
      price: 1000,
      img: "./assets/images/stew_with_beef.png",
    },
    {
      id: "ckr14",
      name: "Stew with Assorted Meat",
      price: 1000,
      img: "./assets/images/Stew-with-Assorted-meat.jpg",
    },
    {
      id: "ckr15",
      name: "Okra with Turkey",
      price: 900,
      img: "./assets/images/Okra-Soup-with-Beef.jpg",
    },
    {
      id: "ckr16",
      name: "Okra with Soft Chicken",
      price: 900,
      img: "./assets/images/okra-soup-with-soft-chicken.png",
    },
    {
      id: "ckr17",
      name: "Okra with Hard Chicken",
      price: 1000,
      img: "./assets/images/Okra-Soup-with-Beef.jpg",
    },
    {
      id: "ckr18",
      name: "Okra with Goat Meat",
      price: 900,
      img: "./assets/images/Okra-Soup-with-Beef.jpg",
    },
    {
      id: "ckr19",
      name: "Okra with Beef",
      price: 900,
      img: "./assets/images/Okra-Soup-with-Beef.jpg",
    },
    {
      id: "ckr20",
      name: "Ogbono with Turkey",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr21",
      name: "Ogbono with Hard chicken",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr22",
      name: "Ogbono with Beef",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr23",
      name: "Ogbono with Assorted",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr24",
      name: "Ogbono with Soft Chicken",
      price: 900,
      img: "./assets/images/ogbona_with_goat_meat.png",
    },
    {
      id: "ckr25",
      name: "Minced Beef Sauce",
      price: 900,
      img: "./assets/images/Minced-Beef-Sauce.jpg",
    },
    {
      id: "ckr26",
      name: "Efo Riro with Turkey",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr27",
      name: "Efo Riro with Chicken",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr28",
      name: "Efo Riro with Hard Chicken",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr29",
      name: "Efo Riro with Goat Meat",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
    {
      id: "ckr30",
      name: "Efo Egusi with Turkey",
      price: 900,
      img: "./assets/images/Efo-Riro.jpg",
    },
  ];
  